notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("viewnote/<int:pk>", views.view_note, name="view_note"),
    path("editnote/<int:note_id>/", views.edit_note, name="edit_note"),
    path("deletenote/<int:pk>", views.delete_note, name="delete_note"),
    path("api/notes/<int:note_id>/", views.get_note_data, name="get_note_data"),
    # path("api/notes/<int:pk>/", views.api_notes, name="api_notes"),
]

todonotes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('',include('notes.urls',namespace="notes")),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Todonote(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    description=models.TextField(max_length=1000)
    notetime=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.username}-{self.title}"

notes/forms.py
from django import forms

from .models import Todonote


class NoteForm(forms.ModelForm):
    class Meta:
        model = Todonote
        fields = ["title", "description"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control my-2", "placeholder": "Enter note title"},
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control my-2",
                    "rows": "3",
                    "placeholder": "Enter note description",
                },
            ),
        }

notes/views.py
from .models import Todonote
from django.contrib.auth.decorators import login_required
from .forms import NoteForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden, JsonResponse
from django.contrib import messages
from django.urls import reverse

# Create your views here.


def home(request):
    form = NoteForm()
    if request.method == "POST":
        if request.user.is_authenticated:
            try:
                form = NoteForm(request.POST)
                if form.is_valid():
                    note = form.save(commit=False)
                    note.username = request.user
                    note.save()
                    messages.success(
                        request,
                        "Your notes added.",
                        extra_tags="alert alert-success alert-dismissible fade show",
                    )
                    return redirect("notes:view_note", note.id)
                else:
                    messages.error(
                        request,
                        "Oops could not add your note.",
                        extra_tags="alert alert-danger alert-dismissible fade show",
                    )
            except Exception:
                messages.error(
                    request,
                    "Oops some error occured",
                    extra_tags="alert alert-danger alert-dismissible fade show",
                )
                pass
            return redirect("notes:home")
        else:
            messages.error(
                request,
                "Please login to add notes.",
                extra_tags="alert alert-primary alert-dismissible fade show",
            )
            return redirect("accounts:login")
    notes = {}
    if request.user.is_authenticated:
        notes = Todonote.objects.filter(username=request.user)

    return render(request, "notes/home.html", {"notes": notes, "form": form})


def about(request):
    if request.user.is_authenticated:
        messages.success(
            request,
            f"Welcome here,  {request.user.username} !!",
            extra_tags="alert alert-primary alert-dismissible fade show",
        )
    else:
        messages.success(
            request,
            "Please login to manage your notes.",
            extra_tags="alert alert-primary alert-dismissible fade show",
        )

    return render(request, "notes/about.html")


@login_required
def view_note(request, pk):
    notes = {}
    try:
        notes = Todonote.objects.filter(username=request.user, pk=pk)
    except Todonote.DoesNotExist:
        messages.error(
            request,
            "Note does not exist.",
            extra_tags="alert alert-danger alert-dismissible fade show",
        )
        pass
    return render(request, "notes/viewnote.html", {"notes": notes})


@login_required
def edit_note(request, note_id):
    # Retrieve the note based on the note_id or return a 404 if not found
    try:
        note = get_object_or_404(Todonote, username=request.user, pk=note_id)
    except Todonote.DoesNotExist:
        messages.error(
            request,
            "Note does not exist.",
            extra_tags="alert alert-danger alert-dismissible fade show",
        )
        return redirect("notes:home")

    # Check if the user has permission to edit the note (e.g., the note's owner)
    if request.user != note.username:
        return HttpResponseForbidden("You don't have permission to edit this note.")

    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            # Optionally, you can return a JSON response indicating success
            messages.success(
                request,
                "Note updated successfully.",
                extra_tags="alert alert-success alert-dismissible fade show",
            )
            # print("Updated note")
            return JsonResponse(
                {"redirect_url": reverse("notes:view_note", args=[note_id])}
            )
            # return redirect("notes:view_note", note_id)
            # return JsonResponse({"message": "Todonote updated successfully"})
        else:
            # If form validation fails, return a JSON response with error details
            errors = form.errors.as_json()
            # messages.error(
            #     request,
            #     "Can't update your note. Please try again.",
            #     extra_tags="alert alert-danger alert-dismissible fade show",
            # )
            return JsonResponse({"errors": errors}, status=400)
    else:
        form = NoteForm(instance=note)

    # Render the HTML template with the form
    # return render(request, 'edit_note.html', {'form': form, 'note': note})
    return redirect("notes:home")


@login_required
def delete_note(request, pk):
    if request.user.is_authenticated:
        try:
            notes = Todonote.objects.filter(username=request.user, pk=pk)
            notes.delete()
            messages.success(
                request,
                "Note deleted",
                extra_tags="alert alert-success alert-dismissible fade show",
            )
        except Todonote.DoesNotExist:
            messages.error(
                request,
                "Note does not exist",
                extra_tags="alert alert-danger alert-dismissible fade show",
            )
            pass
    else:
        messages.error(
            request,
            "Please login to delete your note.",
            extra_tags="alert alert-primary alert-dismissible fade show",
        )
        return redirect("accounts:login")
    return redirect("notes:home")


@login_required
def get_note_data(request, note_id):
    if request.user.is_authenticated:
        if request.method == "POST":
            try:
                note = get_object_or_404(Todonote, pk=note_id)
                note_data = {
                    "id": note_id,
                    "title": note.title,
                    "description": note.description,
                }
                # print(note_data)
                return JsonResponse(note_data)
            except Todonote.DoesNotExist:
                return JsonResponse({"error": "Note does not exist."}, status=400)
        else:
            return redirect("notes:home")
    else:
        return redirect("accounts:login")

templates/notes/about.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
    .card img {
        width: 18rem;
        height: 18rem;
    }
</style>
{% endblock css %}

{% block contents %}
<div class="container my-4 py-5 pb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
    <header class="text-center">
        <h1 class="display-4">About MyNote</h1>
        <p class="lead">Trusted Note Taking Application- 07-12-2023</p>
        <p class="lead">Developed by:<li>Abha Kamble (N01607054)</li><li>Vineela Dandu (N01605093)</li><li>Sudharshan Venkatesh (N01620423)</li></p>
    </header>
</div>
{% endblock contents %}

templates/notes/home.html
{% extends 'base.html' %}


{% block css %}
<link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
    crossorigin="anonymous">
    </script>
<script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
{% endblock css %}


{% block contents %}
<div class="row justify-content-center">
    <div class="col-md-6">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
<div class="my-5 py-5 pb-5" style="min-height: 45rem;">

    <div class="container py-5 pb-5 shadow rounded">
        <h2 class="text-center">MyNote</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">&#x2714;</button>
            <button type="reset" class="btn btn-secondary">&#x2613;</button>
        </form>
    </div>


    <div class="container my-5 pb-5">
        {% if request.user.is_authenticated and notes %}
        <h3 class="text-center">My Notes</h3>
        <table class="table" id="notestable">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Note Time</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for note in notes %}
                <tr>
                    <td class="text-break"><a class="text-decoration-none color-dark"
                            href="{% url 'notes:view_note' note.id %}">{{ note.title|truncatechars:10 }}</a></td>
                    <td>{{ note.notetime|date:"d-m-Y" }}</td>
                    <td class="text-break">{{ note.description | truncatewords:10 }}</td>
                    <td>
                        <span>
                            <button class="btn btn-primary btn-sm editNote" data-bs-toggle="modal"
                                data-bs-target="#editModal" data-note-id="{{note.id}}">&#9999;</button>
                            <a href="{% url 'notes:delete_note' note.id %}" class="btn btn-danger btn-sm">&#x2613;</a>
                        </span>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit Note</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="" method="POST" id="editForm">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input class="form-control" placeholder="Reading book" id="titleEdit"
                                    name="title"></input>
                                <label for="titleEdit">Note Title</label>
                            </div>
                            <div class="form-floating mb-3">
                                <textarea class="form-control" placeholder="I'll read twelfth fail book" id="descEdit"
                                    name="description"></textarea>
                                <label for="descEdit">Note Description</label>
                            </div>
                            <div class="modal-footer d-block">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {% else %}
        <h4 class="text-center my-4">No notes found!!</h4>

        {% endif %}
    </div>
</div>

{% endblock contents %}



{% block js %}
<script>
    $(document).ready(function () {
        $("#notestable").DataTable();
    });

    var editModal = document.getElementById('editModal');
    editModal.addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget;
        var noteId = button.getAttribute('data-note-id');
        var form = document.getElementById('editForm');
        form.action = '/editnote/' + noteId + '/'; // Replace with the correct URL for updating notes
        form.method = "POST";

        // Fetch data using POST method
        fetch('/api/notes/' + noteId + '/', {
            method: 'POST', // Use POST method
            headers: {
                'Content-Type': 'application/json', // Set the content type
                'X-CSRFToken': getCookie('csrftoken') // Include CSRF token
            },
            body: JSON.stringify({}), // An empty request body for the GET request
        })
            .then(function (response) {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(function (data) {
                var titleInput = document.getElementById('titleEdit');
                var descInput = document.getElementById('descEdit');
                titleInput.value = data.title;
                descInput.value = data.description;
            })
            .catch(function (error) {
                console.error('Fetch error:', error);
            });

        // Add a click event handler for the "Save" button
        var saveButton = document.querySelector('#editModal button[type="submit"]');
        saveButton.addEventListener('click', function (e) {
            e.preventDefault(); // Prevent the default form submission

            // Use Fetch API to submit the form data
            fetch(form.action, {
                method: 'POST', // Use POST method
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded', // Set the content type
                    'X-CSRFToken': getCookie('csrftoken') // Include CSRF token
                },
                body: new URLSearchParams(new FormData(form)), // Serialize form data
            })
                .then(function (response) {
                    if (response.ok) {
                        // Handle success, e.g., close the modal and refresh the page
                        $('#editModal').modal('hide'); // Close the modal
                        return response.json();
                    } else {
                        $('#editModal').modal('hide'); // Close the modal
                        throw new Error('Form submission failed');
                    }
                })
                .then(function (data) {
                    // Redirect using the URL from the JSON response
                    window.location.href = data.redirect_url;
                })
                .catch(function (error) {
                    $('#editModal').modal('hide'); // Close the modal
                    console.error('Form submission error:', error);
                });
        });
    });

    // Function to get the CSRF token from cookies
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
{% endblock js %}

templates/notes/viewnote.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    #viewnote {
        background-image: url("{% static 'images/viewnotebg.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        min-height: 100vh;
    }
</style>
{% endblock css %}

{% block contents %}
<div id="viewnote" class="container-fluid d-flex justify-content-center align-items-center">
    <div class="container py-5 bg-secondary text-bg-secondary bg-opacity-75 shadow rounded mb-5">
       <!-- <div class="row justify-content-center py-5">
            <div class="col-md-6">
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div> -->
        {% if request.user.is_authenticated and notes %}
        <div class="text-center">
            <h3 class="mb-4">My Notes</h3>
        </div>
        <div class="row justify-content-center">
            {% for note in notes %}
            <div class="col-md-8">
                <div class="mb-4">
                    <div class="">
                        <h3>Title</h3>
                        <p>{{ note.title }}</p>
                        <h3>Description</h3>
                        <p>{{ note.description }}</p>
                        <h3>Time</h3>
                        <p>{{ note.notetime }}</p>
                        <p> <strong>Author : </strong> {{ note.username }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="text-center">
            <h4>No notes found!</h4>
        </div>
        {% endif %}
    </div>
</div>

<script>
    $(document).ready(function () {
        // Function to adjust container-fluid height based on viewport height
        function adjustContainerHeight() {
            const navbarHeight = $('.navbar').outerHeight();
            const viewportHeight = $(window).height();
            const containerHeight = viewportHeight - navbarHeight;
            $('.container-fluid').css('max-height', containerHeight + 'px');
        }

        // Initial adjustment on page load
        adjustContainerHeight();

        // Adjust on window resize
        $(window).resize(function () {
            adjustContainerHeight();
        });
    });
</script>

{% endblock contents %}